import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    "**/skills",
    // Generated by `react-doctor install`.
    ".cursor/hooks/react-doctor.mjs",
  ],
});
