import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";

export default defineConfig({
  extends: [core, react, tanstack],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    "**/skills",
    // Generated by `react-doctor install`.
    ".cursor/hooks/react-doctor.mjs",
  ],
  overrides: [
    {
      // The Next.js preset only applies to the docs site; its rules (e.g.
      // `no-html-link-for-pages`) misfire on the TanStack Start web app.
      files: ["apps/docs/**"],
      plugins: next.plugins,
      rules: next.rules,
    },
    {
      // Test doubles implement async interfaces without awaiting anything.
      files: ["**/*.test.ts"],
      rules: { "require-await": "off" },
    },
    {
      files: ["apps/api/bin/**/*.ts"],
      rules: { "no-console": "off" },
    },
    {
      files: ["apps/api/src/index.ts"],
      rules: { "import/no-default-export": "off", "no-console": "off" },
    },
    {
      // Frameworks and tools that load these files require a default export.
      files: [
        "oxlint.config.ts",
        "oxfmt.config.ts",
        "apps/docs/app/**",
        "apps/docs/next.config.mjs",
        "apps/docs/open-next.config.ts",
        "apps/web/src/routes/**",
        "apps/web/src/server.ts",
        "apps/web/vite.config.ts",
      ],
      rules: { "import/no-default-export": "off" },
    },
  ],
  rules: {
    // Project conventions carried over from the previous Biome config.
    "import/no-default-export": "error",
    "no-console": "warn",
    "no-restricted-imports": [
      "error",
      {
        paths: [
          { name: ".", message: "Import from the specific module instead." },
          {
            name: "./index",
            message: "Import from the specific module instead.",
          },
        ],
      },
    ],

    // Ultracite prefers arrow-function expressions; this codebase uses
    // hoisted function declarations, so enforce that style instead.
    "func-style": ["error", "declaration", { allowArrowFunctions: true }],
    "no-use-before-define": ["error", { functions: false }],
    "react/function-component-definition": [
      "error",
      { namedComponents: "function-declaration" },
    ],

    // TypeBox models pair a schema value with a same-named type
    // (`const Rate = t.Object(...)` / `type Rate = Static<typeof Rate>`).
    "no-redeclare": "off",

    // Key order is observable in API JSON responses and the OpenAPI schema.
    "sort-keys": "off",

    // `parseFloat`/`parseInt` deliberately tolerate trailing text in scraped
    // values (e.g. "5.95%"), where `Number()` would return NaN.
    "unicorn/prefer-number-coercion": "off",
  },
});
